### ISSUE TITLE
Castaway II by Likwid

### ISSUE THREAD

**Issue by StoneyTBoI** [FlashpointProject/game-bug-tracker#1]
**Flashpoint Version:** 10.1.0.5 Infinity 

**Problem:** HUD and Game are off-centered making the game almost unplayable
**Game UUID:** cca478f9-4a2b-b458-63d7-91f7badd19f7

**Screenshots:**
![Screenshot_1](https://user-images.githubusercontent.com/54912218/160162737-ba831ad0-8cc9-4b4d-af08-3ea7509b296d.png)
![Screenshot_2](https://user-images.githubusercontent.com/54912218/160162740-7d360763-1cab-4cf5-bc22-7ceccc8417d3.png)

(Screenshot_1 is Big window and Screenshot_2 is Small window)

**Comment by n0samu** [comment]
This seems like a game bug. To avoid this problem, just avoid resizing the window.
